### PR TITLE
Added Lithuanian language to batch.ini

### PR DESCRIPTION
**Pull request by CattopyTheWeb**
Added Lithuanian language to batch.ini for my fellow Lithuanian speakers
----------
### Type of change
- [x] New feature (non-breaking change which adds functionality)

### Proposed Changes
- Line 125
- Line 131

### Checklist:

- [No ] I have commented my code, particularly in hard-to-understand areas
- [Yes ] I have tested that the code works

## Required:
- By contributing to this project, you agree to the terms of the GPLv3 license, and agree to grant the project owner the right to also provide or sell this software, including your contribution, to anyone under any other license, with no compensation to you.

### CODE REVIEW

**Comment by CattopyTheWeb** [comment]
Will someone merge my PR?

**Comment by CattopyTheWeb** [comment]
@ThioJoe What do you think?

**Comment by CattopyTheWeb** [comment]
Hello?

**Comment by CattopyTheWeb** [comment]
@ThioJoe Please check this out

**Comment by danielrobin13** [comment]
Hey I am not a coder and I don't know how to use it @thiojoe, please help how can I use this program to add audio tracks to my video

**Comment by danielrobin13** [comment]
Or make a video tutorial with complete steps.

**Comment by CattopyTheWeb** [comment]
> Or make a video tutorial with complete steps.

https://www.youtube.com/watch?v=uaHmtJrZRdM&t=250s

**Comment by ThioJoe** [comment]
Just gonna close this, anyone can add whatever languages they want, it's not necessary to add any more as default, they're mostly just examples

**Comment by CattopyTheWeb** [comment]
> Just gonna close this, anyone can add whatever languages they want, it's not necessary to add any more as default, they're mostly just examples

Well not everyone knows how the config file works. And besides if people are gonna dub videos why not add more language s? I'm sure some fellow Lithuanian citizens would appreciate this.

**Comment by danielrobin13** [comment]
> > Or make a video tutorial with complete steps.
> 
> https://www.youtube.com/watch?v=uaHmtJrZRdM&t=250s

I have already seen this video, but I want complete steps to add languages, as in this video thio sir only explained how the program works. It will be useful for everyone if you make a complete tutorial on how to do it step by step.

**Comment by CattopyTheWeb** [comment]
Hmm

**Pull request closed without merging**
